language: go
go:
  - 1.6
script: go test ./...
install:
  - go get -u github.com/Masterminds/glide
  - glide install
  - glide up
notifications:
  slack:
    secure: pFVHVnCQkM6NHsmVvv12CoxNSH8N8VwET+sOTXmiIhl1yoZB5lg29AXNUMAvXa1A1YatA+WxV65Bq7oxQ1TEtgQSzDNSW6fcCfyN292+OgGH8xY6+5bB8GFWPYCvxhYBqVnmdDevKtDyF7YnWT+RmeyN/vtaCt1VVZ6ssFRIAg1go+j1+g9/1IiYIvgrIfMmGGMhWfIiGNKbKpUxTtt5vFH3FyScnkqEqRwf/BtRAylz88oR6yqjLHt5CNtCQXGCpOOBznUXskTAZU78FSvF2EPXNquchX26Q2n7tfZjGvyXmw4Ls5G4YICC6i9lOoXK8iaY6UYNF9ctx2/SGH5H8YpFcsRIjczu/3UlqIRkV5kB38LWU7S+dFhM3ugGnk7b7mYPMLaejxV/IU668UVno67vYwoyCYWXq+vZ0u+dRqS64NlE7duvVH159nWkF2/OnE5kv9QBrTLRdMwatIdQyh8bH94/C2eqQJUkvyGDCKhmgyLyJR7fXVoh1Syq7oOMEtX2VvhjlixLmPmzXeKTBskwmJIdKDESGl9SlWfbKSzJ4RK/Ji4gpiihv3vIAYSgsdxgUGsBV9HvwtQw8Ewnxg516pfPSkAMesUovFaMzbjr2gfT0uIyMRFX7nqC0HfjAt6w/FVtbWmzV2A11WkTRyrQdGui9UtgI89h/1FifD4=
